export interface SpecFile {
  id: string;
  name: string;
  category: 'Governance' | 'Physics Contract' | 'Solver Kernel' | 'Test Harness' | 'Mission Fit';
  language: 'markdown' | 'python';
  path: string;
  description: string;
  content: string;
}

export const SPEC_FILES: SpecFile[] = [
  {
    id: 'claim_gov',
    name: 'CLAIM_GOVERNANCE.md',
    category: 'Governance',
    language: 'markdown',
    path: 'CLAIM_GOVERNANCE.md',
    description: 'The core epistemic governance contract enforcing fail-closed assertions on research claims.',
    content: `# CLAIM GOVERNANCE PROTOCOL (v1.4)
# Epistemic Gate & Evidence Enforcement Standard

## 1. Principles of Anti-Hype Governance
All assertions generated by or derived from the \`heimdall-electra\` codebase must strictly map to one of four mutually exclusive Evidence Classes. Under no circumstance may downstream documentation, papers, or UI consoles promote a claim beyond its active verified class.

## 2. Evidence Class Hierarchy
- **CLASS 0 (ANALYTICAL)**: Mathematical derivation or forward-model theory. (Permitted: "Theoretical formulation indicates...")
- **CLASS 1 (SYNTHETIC)**: Validated against synthetic datasets, mock RF feeds, or numerical simulations. (Permitted: "Synthetic simulation exhibits convergence with GDOP < 3.2...")
- **CLASS 2 (LABORATORY / HIL)**: Verified inside a physical vacuum plasma chamber or hardware-in-the-loop SDR testbench. (Permitted: "Laboratory SDR replay demonstrates 14dB SNR recovery...")
- **CLASS 3 (OBSERVED ON-ORBIT)**: Formally cross-correlated against flight sensor telemetry and independent optical/radar ground truth. (Permitted: "Empirical detection of NORAD #54321 confirmed...")

## 3. Machine-Checked Assertion Rules
\`\`\`python
def assert_claim_validity(claim_text: str, evidence_tier: EvidenceClass) -> None:
    for prohibited_pattern in PROHIBITED_DETECTION_PATTERNS:
        if prohibited_pattern.search(claim_text) and evidence_tier < EvidenceClass.OBSERVED:
            raise EpistemicGovernanceViolation(
                f"Fail-Closed Violation: '{claim_text}' asserts on-orbit detection "
                f"without Class 3 evidence attached."
            )
\`\`\`

## 4. SHA-256 Audit Chain
Every simulation run produces an immutable JSON-LD execution bundle signed with SHA-256 hash chains to prevent cherry-picked parameter optimization.`
  },
  {
    id: 'physics_contract',
    name: 'PHYSICS_INPUT_CONTRACT.md',
    category: 'Physics Contract',
    language: 'markdown',
    path: 'PHYSICS_INPUT_CONTRACT.md',
    description: 'Interface definition for ionospheric plasma parameters and hypersonic wake excitation.',
    content: `# PHYSICS INPUT & FORWARD MODEL CONTRACT

## 1. Dimensional Units & Precision
- Time: Seconds (UTC / GPS seconds), sub-nanosecond timestamping precision.
- Velocity: Meters per second (m/s), Earth-Centered Inertial (ECI J2000).
- Plasma Density ($n_e$): Electrons per cubic meter ($10^{10} - 10^{12} \\text{ m}^{-3}$).
- Electron Temperature ($T_e$): Electron volts (eV), typical LEO range 0.1 - 0.3 eV.

## 2. Hypersonic Mach Cone Formulations
For an orbital object with velocity $v_{orb} \\approx 7.6 \\text{ km/s}$ traversing ion acoustic velocity $c_s = \\sqrt{k_B T_e / m_i} \\approx 1.5 - 2.5 \\text{ km/s}$:

$$\\text{Mach Number } M = \\frac{v_{orb}}{c_s} \\approx 3.0 - 5.5$$
$$\\text{Mach Cone Half-Angle } \\theta_M = \\arcsin\\left(\\frac{1}{M}\\right)$$

## 3. Debye Sheath & Wake Extent
The characteristic Debye shielding length is computed as:
$$\\lambda_D = \\sqrt{\\frac{\\varepsilon_0 k_B T_e}{n_e e^2}}$$

The wake perturbation trail extends downstream over a characteristic relaxation length:
$$L_{wake} \\approx M \\cdot \\lambda_D \\cdot \\left(\\frac{r_{debris}}{\\lambda_D}\\right)^{2/3}$$`
  },
  {
    id: 'tdoa_solver',
    name: 'tdoa_solver.py',
    category: 'Solver Kernel',
    language: 'python',
    path: 'src/heimdall/tdoa_solver.py',
    description: 'Non-linear least squares Time-Difference of Arrival multilateration with GDOP covariance bounds.',
    content: `"""
Heimdall-Electra: High-Precision TDOA Multilateration Kernel
Author: Aarti S Ravikumar (@aartisr)
License: Apache-2.0
"""

from dataclasses import dataclass
from typing import List, Tuple
import numpy as np

SPEED_OF_LIGHT = 299_792_458.0  # m/s in vacuum

@dataclass(frozen=True)
class ReceiverNode:
    node_id: str
    position_eci: np.ndarray  # [x, y, z] in meters
    clock_bias_std_ns: float  # standard deviation in ns

@dataclass
class TDOAMeasurement:
    receiver_pair: Tuple[str, str]
    delta_t_seconds: float
    snr_db: float
    quality_flag: int

def solve_hyperbolic_position(
    receivers: List[ReceiverNode],
    measurements: List[TDOAMeasurement],
    initial_guess: np.ndarray,
    max_iter: int = 50,
    tolerance: float = 1e-4
) -> Tuple[np.ndarray, np.ndarray, float]:
    """
    Solves for target 3D Cartesian coordinates via Gauss-Newton 
    Non-Linear Least Squares with covariance matrix extraction.
    """
    pos = np.copy(initial_guess).astype(float)
    rx_map = {r.node_id: r.position_eci for r in receivers}
    
    for iteration in range(max_iter):
        residuals = []
        jacobian = []
        
        for m in measurements:
            rx_a = rx_map[m.receiver_pair[0]]
            rx_b = rx_map[m.receiver_pair[1]]
            
            d_a = np.linalg.norm(pos - rx_a)
            d_b = np.linalg.norm(pos - rx_b)
            predicted_delta_t = (d_a - d_b) / SPEED_OF_LIGHT
            
            residuals.append(m.delta_t_seconds - predicted_delta_t)
            
            # Analytical Jacobian gradient vector
            grad_a = (pos - rx_a) / (d_a * SPEED_OF_LIGHT)
            grad_b = (pos - rx_b) / (d_b * SPEED_OF_LIGHT)
            jacobian.append(grad_a - grad_b)
            
        J = np.array(jacobian)
        r = np.array(residuals)
        
        # Normal equations: (J^T J) delta = J^T r
        JTJ = J.T @ J
        if np.linalg.cond(JTJ) > 1e12:
            raise FloatingPointError("Ill-conditioned GDOP geometry matrix")
            
        delta = np.linalg.solve(JTJ, J.T @ r)
        pos += delta
        
        if np.linalg.norm(delta) < tolerance:
            cov = np.linalg.inv(JTJ)
            gdop = np.sqrt(np.trace(cov))
            return pos, cov, float(gdop)
            
    raise TimeoutError(f"TDOA solver failed to converge after {max_iter} iterations")`
  },
  {
    id: 'test_physics',
    name: 'test_physics_relations.py',
    category: 'Test Harness',
    language: 'python',
    path: 'tests/test_physics_relations.py',
    description: 'Metamorphic invariance tests validating physical laws, charge scaling, and inverse square potential decay.',
    content: `"""
Metamorphic Physics Invariance Test Suite
Validates that forward models strictly obey fundamental physical laws.
"""

import pytest
import numpy as np
from heimdall.physics.wake import calculate_wake_potential, calculate_mach_cone

def test_wake_potential_monotonic_with_charge():
    """Metamorphic Invariant 1: Higher debris charge MUST yield strictly higher wake potential."""
    distances = np.linspace(10, 500, 20)
    potentials_q1 = [calculate_wake_potential(r, charge_coulombs=1e-12) for r in distances]
    potentials_q2 = [calculate_wake_potential(r, charge_coulombs=5e-12) for r in distances]
    
    for p1, p2 in zip(potentials_q1, potentials_q2):
        assert p2 > p1, f"Monotonicity violation: q2 potential {p2} <= q1 potential {p1}"

def test_wake_amplitude_inverse_decay():
    """Metamorphic Invariant 2: Wake amplitude must decay monotonically with distance r."""
    r_near = calculate_wake_potential(r=20.0, charge_coulombs=1e-12)
    r_far = calculate_wake_potential(r=200.0, charge_coulombs=1e-12)
    assert r_near > r_far * 5.0, "Decay rate fails asymptotic physical decay bounds"

def test_mach_cone_angle_invariance():
    """Metamorphic Invariant 3: Mach angle theta = arcsin(1/M) must decrease with velocity."""
    mach_low = calculate_mach_cone(v_orbital=5000.0, c_sound=1500.0)   # M = 3.33
    mach_high = calculate_mach_cone(v_orbital=8000.0, c_sound=1500.0)  # M = 5.33
    assert mach_high.half_angle_rad < mach_low.half_angle_rad, "Mach angle failed kinematic compression"`
  },
  {
    id: 'mission_fit',
    name: 'Wiki_NASA_Mission_Fit.md',
    category: 'Mission Fit',
    language: 'markdown',
    path: 'wiki/Wiki_NASA_Mission_Fit.md',
    description: 'Analysis of alignment with NASA ODPO (Orbital Debris Program Office) and AFRL Space Domain Awareness priorities.',
    content: `# NASA & DoD MISSION ALIGNMENT ANALYSIS

## 1. Strategic Context
Over 500,000 pieces of orbital debris between 1 mm and 10 cm populate Low Earth Orbit (LEO). Conventional ground-based SSN (Space Surveillance Network) radar and optical telescopes cannot reliably track sub-5cm objects due to $R^{-4}$ radar cross-section attenuation.

## 2. The Heimdall-Electra Opportunity
Passive electromagnetic plasma wake sensing bypasses $R^{-4}$ two-way radar power laws by listening to the **in-situ acoustic and RF shock excitation** generated as the charged debris sweeps through the ionosphere at $7.5 \\text{ km/s}$.

## 3. NASA Program Office Intersections
- **NASA ODPO**: Complements the Debris Assessment Software (DAS) and B-plane conjunction assessments.
- **NASA NIAC Phase I/II**: High-risk, transformative space technology candidate.
- **AFRL Space Domain Awareness**: Distributed multi-static nanosatellite constellation payloads.`
  }
];
